### PR TITLE
saikrishna.D

### PR DESCRIPTION
**Pull request by saikrishna76**
This code refers about selection of items from the given list of items and their quantity.ex output is shown in below
Select items from the list:

1.USPA SLIM-FIT	RS.2000

2.AXE PERFUME	RS.200
3.SHIRT-ARROW	RS.1000
4.BELT-LEATHER	RS.300
5.SHOE-PUMA	RS.1500

select the item number:
1
enter quantity:
1
Add more Items?(y,n):
y
Select items from the list:

1.USPA SLIM-FIT	RS.2000

2.AXE PERFUME	RS.200
3.SHIRT-ARROW	RS.1000
4.BELT-LEATHER	RS.300
5.SHOE-PUMA	RS.1500

select the item number:
3
enter quantity:
1
Add more Items?(y,n):
n

 1. Check out 
 2. Cancel the order 

Enter option:
1
==========================================

Item	Quantity
==========================================

AXE PERFUME(RS.200)	1

BELT-LEATHER(RS.300)	1

USPA SLIM-FIT(RS.2000)	0

USPA SLIM-FIT(RS.2000)	0

USPA SLIM-FIT(RS.2000)	0

USPA SLIM-FIT(RS.2000)	0
==========================================

Total Bill:3000
==========================================

### CODE REVIEW

**Comment by sushil-rxr** [comment]
@saikrishna76, please do not send a pull request before you are ready with your complete assignment. You should commit code to your forked repository (https://github.com/saikrishna76/freshers-java-assignment.git), not the main repository.

**Comment by saikrishna76** [comment]
hi sir,
sorry sir. While learning about using of github it is happened. You
mentioned closed#1. may I know what is that. For god sake it should not be
the elimination.

**Comment by sushil-rxr** [comment]
Ha ha no not for elimination. Dont be so scared. Closing a pull request means rejecting it. If I accept your code will get merged into the main repository which is not what we want do we? :-)

Please carry on the good work.

**Comment by saikrishna76** [comment]
Oh thank god. I am really scared about that.But its really fantastic experience.Thank you sir.

**Pull request closed without merging**
